### ISSUE TITLE
Fix the displaying of admins in cohort metrics, i.e. added admins are not shown.

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#105]
Admins are neither displayed nor saved.

![Image](https://user-images.githubusercontent.com/104435781/243346343-83c1fdd2-1dc2-4943-89ec-95996a1820dd.png)
![Image](https://user-images.githubusercontent.com/104435781/243346342-ac92688b-114a-4ca7-9f9f-8f230b573b54.png)

**Comment by benedictvscriticus** [comment]
This also applies for the admin management in cohort management.

![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/104435781/3edd11b6-6f57-4dba-b474-0b5a92452860)

**Comment by benedictvscriticus** [comment]
Hunter is hooking up the contract calls to the frontend. Ken is integrating sub-graph into the frontend for admins to be shown.

**Comment by hking2** [comment]
The contract is hooked up for minting Hats. The code is there for Transfers, but i'll wait to properly hook that part up until the subGraph displays current admins, so i can put an `if / else` to choose to mint or transfer based on who is/isn't wearing hats

**Comment by hking2** [comment]
i can't test this without being able to deploy a cohort...

**Comment by hking2** [comment]
![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/50965054/b02cbf28-fdc5-4207-93ca-f89660cfcfaa)

**Comment by hking2** [comment]
fixed
