### ISSUE TITLE
I cannot approve to stake nor sponsor an initiate.

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#107]
![Image](https://user-images.githubusercontent.com/104435781/243358580-e943988a-c5e0-4ef3-b986-25f93c7535c9.png)

**Comment by hking2** [comment]
![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/50965054/33cc00a8-be0b-4d58-b204-0f378080bed5)

**Comment by hking2** [comment]
staking for user works. but need to fix for sponsor

**Comment by hking2** [comment]
![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/50965054/dd098f45-9778-4477-bad3-2e1e0e17c761)
