### ISSUE TITLE
fix link on metrics page

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#108]
![Image](https://user-images.githubusercontent.com/104435781/243388986-c84c3e63-61a4-43c2-a898-2b763f8dbcb7.png)

**Comment by hking2** [comment]
![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/50965054/189488db-5dce-4d95-9b69-495e632c8dd2)

**Comment by hking2** [comment]
Links format and route correctly now
