### ISSUE TITLE
Slashing function does not work

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#120]
- no success message in manual slashing modal
- slashed members do not show up in metrics
- stake of member does not change from 1 to 0

![Image](https://user-images.githubusercontent.com/104435781/243643863-112a6a6d-0480-4076-b5c9-078bded5ece9.png)

![Image](https://user-images.githubusercontent.com/104435781/243644416-fd7e6788-2c4c-4863-b135-05fbf467a1a7.png)

![Image](https://user-images.githubusercontent.com/104435781/243644511-84f66b3d-53cd-4ec4-9ce0-1722b9548c83.png)

**Comment by benedictvscriticus** [comment]
add sacrifice to cohort and make slashing individual members 'slaughter'.

**Comment by hking2** [comment]
fixed
