### ISSUE TITLE
overflowing column in metrics

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#137]
![Image](https://user-images.githubusercontent.com/104435781/244893125-50c8e7e5-f4d6-4f3d-85c6-e1de99205a60.png)

**Comment by hking2** [comment]
![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/50965054/b435ddfe-4231-4f04-ad48-11ce3f740b1a)

**Comment by hking2** [comment]
fixed
