### ISSUE TITLE
update UI to allow input of exact offering for Shaman deployment

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#139]

**Comment by hking2** [comment]
we should implement this from the smart contract; `require msg.value` on createCohort function call. this will include the fee in the MetaMask tx and not need an actual input on the frontend

**Comment by hking2** [comment]
1. require offering amount to Factory
2. send offering amount to Clone, before calling initialize
3. on initialize, Shaman prop is sent and requires the offering amount from RoM

**Comment by hking2** [comment]
add irl test
