### ISSUE TITLE
add fee disclaimer to landing page

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#143]

**Comment by hking2** [comment]
landing page? shouldn't this happen somewhere in the `createCohort` form

**Comment by hking2** [comment]
actually will put it on the staking component

**Comment by hking2** [comment]
![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/50965054/89f83e8b-fcfa-48e3-bac5-17987907b6d1)
