### ISSUE TITLE
fix up decimals for ERC20 token allowance

### ISSUE THREAD

**Issue by personnamedmike** [rite-of-moloch/RiteOfMoloch-v1.0#57]
Works fine for TST token (which spends Goerli ETH), but when approving ERC20 tokens, there are too many decimal places

**Comment by hking2** [comment]
in createCohort flow

**Comment by bitbeckers** [comment]
Similar/duplicate to #93

**Comment by hking2** [comment]
![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/50965054/5f5cf023-7c47-4136-a04a-48e95ce5a3ac)

**Comment by hking2** [comment]
only formatted for 18 decimals atm
