### ISSUE TITLE
Fix frontend functionality

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#65]

**Comment by benedictvscriticus** [comment]
Ensure subgraph hooks and contract hooks are working properly and potentially fix alignment

**Comment by bitbeckers** [comment]
This is a little vague. The app was updated to use the Graphclient and I'm gradually replacing contract calls with Graph data because that reduces the amount of calls. Since I notice things render it appears to be fine?

Let's review during our chat tomorrow?

**Comment by benedictvscriticus** [comment]
@bitbeckers sounds good, and apologies for the vagueness

**Comment by hking2** [comment]
can i close this? it is vague and taking up space
