### ISSUE TITLE
Engage in orange DAO accelerator

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#73]
- discuss with @hking2 and @bitbeckers
- write application
- https://fellowship.orangedao.xyz/

![Image](https://user-images.githubusercontent.com/104435781/241304746-6fa30418-4531-4067-a8d8-72b55119a85d.png)

**Comment by benedictvscriticus** [comment]
Do you guys want to participate yes/no?

**Comment by hking2** [comment]
yes

**Comment by bitbeckers** [comment]
Upvote

**Comment by benedictvscriticus** [comment]
![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/104435781/da926aa6-bf87-4645-9c41-e4d5be58cfe1)
