### ISSUE TITLE
Infinite load everywhere

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#87]
## Manage Staked members

![Image](https://user-images.githubusercontent.com/104435781/242123823-ae7a65e7-52f3-4679-9846-3e63509d4318.png)

## Manage cohorts

![Image](https://user-images.githubusercontent.com/104435781/242123866-88b6e74f-26a1-4aea-8043-0345e1d5ca9a.png)

## Manage staked members of cohort

manage cohorts -> manage on individual cohort

![Image](https://user-images.githubusercontent.com/104435781/242123915-4e5299e8-49ae-4eb5-9610-967e37025a8c.png)

##

**Comment by bitbeckers** [comment]
Should be fixed
