### ISSUE TITLE
When clicking on 'stake' as a cohort member, the popup crashes.

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#89]
A possible cause is that it's the wrong network (Goerli cohort) selected when on Gnosis chain. Also there are the weird brackets again.

![Image](https://user-images.githubusercontent.com/104435781/242123340-e8739d4e-84aa-44a5-85f3-96e33ab7d5a9.png)

**Comment by bitbeckers** [comment]
Weird brackets are gone

<img width="1008" alt="Screenshot 2023-06-05 at 04 34 27" src="https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/19667964/07308152-2f0b-4467-a8b9-2341c2e9e8ef">

Stake page is sticking (was a logic error)

<img width="1044" alt="Screenshot 2023-06-05 at 04 40 35" src="https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/19667964/fecea550-0c23-432d-85ba-cef652593c44">
