### ISSUE TITLE
when navigating the application, the 'slay or be slain' screen pops up and then the app redirects.

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#91]
![Image](https://user-images.githubusercontent.com/104435781/242380789-bf350a35-2c51-4106-bb88-1e1662dfed2d.png)

**Comment by bitbeckers** [comment]
These little nuggets are spread everywhere throughou the application. This is probably the cause. Would you like them to be gone? I think the app can do a lot in 'read-only' mode so the method below might be a little overkill

```js
  if (!isConnected) {
    return <NotConnected />;
  }
  ```

**Comment by benedictvscriticus** [comment]
As a user, especially when the connection is bad, this bugs me a lot and I can foresee others unnecessarily refreshing the page because of it. So if it doesn't harm the functionality, I'd say we get rid of it wherever possible. What do you think @hking2?

**Comment by hking2** [comment]
yeah, get rid of it!

**Comment by bitbeckers** [comment]
In coolhats branch, WIP
