### ISSUE TITLE
Display staking asset amount in WEI AND UNITs, display staking asset icon, and give option whether to use WEI or units

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#93]
![Image](https://user-images.githubusercontent.com/104435781/242914197-f79e7fe7-4e59-456e-bf52-e975fa45cf2f.png)

**Comment by bitbeckers** [comment]
This is now in the summon form step 2. If you approve, I can wire it up to contract calls to get the symbol and decimals based on the contract address

<img width="707" alt="Screenshot 2023-06-05 at 04 32 18" src="https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/19667964/dc7aa2b5-d667-4d1a-9fe5-8867e91d07ed">
<img width="733" alt="Screenshot 2023-06-05 at 04 32 14" src="https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/19667964/1d8f5ae1-bf49-4acd-a184-1bb06552ed94">
