### ISSUE TITLE
When selecting back on preview cohort, the user is redirected to the menu page. Then when selecting deploy cohort, the user is redirected to the preview cohort page. Then after selecting back all values are erased.

### ISSUE THREAD

**Issue by benedictvscriticus** [rite-of-moloch/RiteOfMoloch-v1.0#95]
Occurred in deployment of https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/pull/92

**Comment by hking2** [comment]
![Image](https://github.com/rite-of-moloch/RiteOfMoloch-v1.0/assets/50965054/2cbb4e43-9bdd-483c-9306-6cc121b11c0e)

**Comment by hking2** [comment]
i get this screen, and it routes as expected

**Comment by benedictvscriticus** [comment]
magically disappeared
